esphome:
  name: bthome-decoder5

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: !secret mqtt_username
  id: mqtt_client

external_components:
  - source:
      type: local
      path: custom_components/bthome_tracker

bthome_tracker:
  id: my_bthome_tracker

esp32_ble_tracker:
  scan_parameters:
    active: true
    duration: 10s
    interval: 500ms
    window: 480ms