sensor:
  - platform: ble_rssi
    mac_address: '38:1F:8D:58:11:57'
    name: "RSSI BT2BEE-BTH01"
    filters:
      - filter_out: nan
      - median:
          window_size: 10

  - platform: template
    name: "BT2BEE-BTH01 Temperature"
    id: BT2BEE_BTH01_temperature_
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - median:
          window_size: 7
          send_every: 6

  - platform: template
    name: "BT2BEE-BTH01 Humidity"
    id: BT2BEE_BTH01_humidity_
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - median:
          window_size: 7
          send_every: 6

  - platform: template
    name: "BT2BEE-BTH01 Voltage"
    id: BT2BEE_BTH01_volt_
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - median:
          window_size: 7
          send_every: 6
